#!/usr/bin/env bash
#
# Generated by: https://openapi-generator.tech
#

dotnet restore /Map.Contract/ && \
    dotnet build /Map.Contract/ && \
    echo "Now, run the following to start the project: dotnet run -p /Map.Contract/Map.Contract.csproj --launch-profile web"
